"""initial migration

Revision ID: ff1a5223eb0e
Revises: 
Create Date: 2025-12-13 12:33:09.771286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1a5223eb0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_age', sa.Integer(), nullable=True),
    sa.Column('user_weight', sa.Float(), nullable=True),
    sa.Column('user_goal', sa.String(), nullable=True),
    sa.Column('plan_title', sa.String(), nullable=True),
    sa.Column('calories_total', sa.Integer(), nullable=True),
    sa.Column('protein_total', sa.Integer(), nullable=True),
    sa.Column('carbs_total', sa.Integer(), nullable=True),
    sa.Column('fat_total', sa.Integer(), nullable=True),
    sa.Column('meals_json', sa.JSON(), nullable=True),
    sa.Column('notes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_plans_id'), 'diet_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diet_plans_id'), table_name='diet_plans')
    op.drop_table('diet_plans')
    # ### end Alembic commands ###
